import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  CHINESE_ARTIST_DROP_LIST,
  isInChineseDropList,
} from '../../../src/adapters/tj-media-direct/chineseArtistDropList.js';
import { normalizeForMatch } from '../../../src/adapters/tj-media-direct/normalize.js';

describe('chineseArtistDropList — Cantopop / Mandopop seed list', () => {
  // Every observed surface form from the 2026-05-06 audit. Three of these
  // (BEYOND, Twins) appeared in multiple cases on different records, hence
  // the explicit case-sensitive variants — they all collapse to the same
  // pre-normalized key, but the raw list documents what was observed.
  const ALL_VARIANTS: readonly string[] = [
    'BEYOND',
    'Beyond',
    'beyond',
    'F4',
    'S.H.E',
    'Twins',
    'twins',
    'TWINS',
    'R1SE',
    'B.A.D',
    'F.I.R.',
    'Marry-M',
    'NZBZ',
  ];

  it('exports a Set covering every observed surface form (post-normalize)', () => {
    for (const variant of ALL_VARIANTS) {
      const key = normalizeForMatch(variant);
      expect(
        CHINESE_ARTIST_DROP_LIST.has(key),
        `variant ${variant} (key=${key}) should be in the set`,
      ).toBe(true);
    }
  });

  it('case variants collapse to the same normalized key (BEYOND family)', () => {
    expect(normalizeForMatch('BEYOND')).toBe(normalizeForMatch('Beyond'));
    expect(normalizeForMatch('BEYOND')).toBe(normalizeForMatch('beyond'));
    expect(CHINESE_ARTIST_DROP_LIST.has(normalizeForMatch('BEYOND'))).toBe(true);
  });

  it('case variants collapse to the same normalized key (Twins family)', () => {
    expect(normalizeForMatch('Twins')).toBe(normalizeForMatch('twins'));
    expect(normalizeForMatch('Twins')).toBe(normalizeForMatch('TWINS'));
    expect(CHINESE_ARTIST_DROP_LIST.has(normalizeForMatch('Twins'))).toBe(true);
  });
});

describe('isInChineseDropList — exact-match (post-normalize) semantics', () => {
  it('returns true for the canonical pre-normalized key (BEYOND)', () => {
    expect(isInChineseDropList(normalizeForMatch('BEYOND'))).toBe(true);
  });

  it('case-insensitive via the normalize step (`Beyond`, `beyond` both match)', () => {
    expect(isInChineseDropList(normalizeForMatch('Beyond'))).toBe(true);
    expect(isInChineseDropList(normalizeForMatch('beyond'))).toBe(true);
  });

  it('whitespace-collapse via the normalize step (`  beyond  ` matches)', () => {
    // Smoke-test that the parser hot-path normalization (which collapses
    // whitespace) reduces to the same key. Direct un-normalized lookup is
    // out of scope — the parser always normalizes before calling.
    expect(isInChineseDropList(normalizeForMatch('  beyond  '))).toBe(true);
  });

  it('returns false on the empty string (defensive)', () => {
    expect(isInChineseDropList('')).toBe(false);
  });

  it('returns false for a real Japanese act with similar surface form', () => {
    // Sanity: 米津玄師 must NOT match — drop list is for Chinese acts only.
    expect(isInChineseDropList(normalizeForMatch('米津玄師'))).toBe(false);
    // YOASOBI must NOT match.
    expect(isInChineseDropList(normalizeForMatch('YOASOBI'))).toBe(false);
  });

  it('returns false for an unrelated string with no overlap', () => {
    expect(isInChineseDropList(normalizeForMatch('not on the list'))).toBe(false);
  });
});

describe('chineseArtistDropList — sidecar JSON staleness check', () => {
  // The sidecar at `packages/crawler/src/adapters/tj-media-direct/
  // chinese-artist-drop-list.json` is the source-of-truth for the Python
  // consumer (`scripts/drop_cpop_leaks.py`). It is regenerated by
  // `scripts/export-chinese-drop-list.mjs` (which the crawler's `build`
  // script invokes after `tsc -b`). Tracking the file in git makes a
  // forgotten regen visible at code-review time — this test makes the same
  // mismatch visible at test time too.
  //
  // If this test fails, run `corepack pnpm --filter @karaoke/crawler build`
  // (or `node scripts/export-chinese-drop-list.mjs` directly after a
  // previous build) to regenerate the sidecar.
  const HERE = dirname(fileURLToPath(import.meta.url));
  const SIDECAR_PATH = resolve(
    HERE,
    '../../../src/adapters/tj-media-direct/chinese-artist-drop-list.json',
  );

  interface SidecarShape {
    version: number;
    keys: string[];
  }

  it('sidecar JSON file exists at the tracked src/ path', () => {
    expect(() => readFileSync(SIDECAR_PATH, 'utf-8')).not.toThrow();
  });

  it('sidecar `keys.length` matches CHINESE_ARTIST_DROP_LIST.size (regen check)', () => {
    const raw = readFileSync(SIDECAR_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as SidecarShape;
    expect(Array.isArray(parsed.keys)).toBe(true);
    expect(parsed.keys.length).toBe(CHINESE_ARTIST_DROP_LIST.size);
  });

  it('sidecar contains every CHINESE_ARTIST_DROP_LIST entry', () => {
    const raw = readFileSync(SIDECAR_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as SidecarShape;
    const sidecarKeys = new Set(parsed.keys);
    for (const k of CHINESE_ARTIST_DROP_LIST) {
      expect(sidecarKeys.has(k)).toBe(true);
    }
  });
});
