import { describe, expect, it } from 'vitest';
import { POST_CATEGORY_OVERRIDES } from '../../../src/adapters/jpop-playlist-blog/crawler.js';

/**
 * Pin the per-post category override map's contents. The map is the
 * source-of-truth for the JSON sidecar generated by
 * `scripts/export-post-category-overrides.mjs` (consumed by the Python
 * corpus retag at `scripts/retag-blog-vocaloid-mistags.py`). If a future
 * edit silently widens or shrinks the map without updating the audit doc
 * (`POST_CATEGORY_OVERRIDES` jsdoc + companion tests), this assertion will
 * flag the regression.
 */
describe('POST_CATEGORY_OVERRIDES — pinned audit set', () => {
  it("has the three audited post-ids ('101', '105', '112') mapped to 'jpop'", () => {
    expect(POST_CATEGORY_OVERRIDES['101']).toBe('jpop');
    expect(POST_CATEGORY_OVERRIDES['105']).toBe('jpop');
    expect(POST_CATEGORY_OVERRIDES['112']).toBe('jpop');
  });

  it('contains AT LEAST the three original audited entries', () => {
    // Lower-bound check — broadening the map (audit-justified additions) is
    // allowed; silently dropping any of the original three is not.
    const keys = Object.keys(POST_CATEGORY_OVERRIDES);
    expect(keys).toEqual(expect.arrayContaining(['101', '105', '112']));
  });
});
