DROP INDEX IF EXISTS idx_song_categories_category;
DROP TABLE IF EXISTS song_categories;
DROP INDEX IF EXISTS idx_search_texts_compact;
DROP INDEX IF EXISTS idx_search_texts_song;
CREATE TABLE IF NOT EXISTS search_texts_new (song_id TEXT NOT NULL REFERENCES songs(id) ON DELETE CASCADE, field TEXT NOT NULL CHECK (field IN ('title_primary', 'title_ko', 'artist_primary', 'artist_ko', 'artist_alias')), text_norm TEXT NOT NULL, text_compact TEXT NOT NULL, weight INTEGER NOT NULL, provider_mask INTEGER NOT NULL, PRIMARY KEY (song_id, field, text_compact));
INSERT INTO search_texts_new (song_id, field, text_norm, text_compact, weight, provider_mask) SELECT song_id, field, text_norm, text_compact, weight, provider_mask FROM search_texts;
DROP TABLE search_texts;
ALTER TABLE search_texts_new RENAME TO search_texts;
CREATE INDEX IF NOT EXISTS idx_search_texts_compact ON search_texts(text_compact, song_id);
CREATE INDEX IF NOT EXISTS idx_search_texts_song ON search_texts(song_id);
DROP INDEX IF EXISTS idx_search_tokens_lookup;
DROP INDEX IF EXISTS idx_search_tokens_song;
CREATE TABLE IF NOT EXISTS search_tokens_new (kind TEXT NOT NULL CHECK (kind IN ('term', 'prefix', 'gram2', 'gram3', 'initial')), token TEXT NOT NULL, song_id TEXT NOT NULL REFERENCES songs(id) ON DELETE CASCADE, field TEXT NOT NULL CHECK (field IN ('title_primary', 'title_ko', 'artist_primary', 'artist_ko', 'artist_alias')), weight INTEGER NOT NULL, provider_mask INTEGER NOT NULL, PRIMARY KEY (kind, token, song_id, field));
INSERT INTO search_tokens_new (kind, token, song_id, field, weight, provider_mask) SELECT kind, token, song_id, field, weight, provider_mask FROM search_tokens;
DROP TABLE search_tokens;
ALTER TABLE search_tokens_new RENAME TO search_tokens;
CREATE INDEX IF NOT EXISTS idx_search_tokens_lookup ON search_tokens(kind, token, song_id);
CREATE INDEX IF NOT EXISTS idx_search_tokens_song ON search_tokens(song_id);
