/**
 * Artist seed list for the `tj-media-direct` adapter's artist-fanout
 * enumeration strategy.
 *
 * What this is:
 *   TJ Media's accompaniment search caps each query at ~200 results and
 *   requires a non-empty `searchTxt`. The adapter therefore enumerates the
 *   catalog by feeding each name in this list into
 *   `?strType=2&searchTxt=<name>` and walking pages 1–2.
 *
 * How it was seeded:
 *   1. Took the union of unique `artist_primary` values from
 *      `apps/web/public/data/songs.json` (the v1 blog corpus, ~350 names
 *      after splitting pipe-separated alias pairs and dropping Korean-only
 *      entries that won't match against `nationType=JPN`).
 *   2. Reduced to a curated subset of well-known mainstream J-POP, Vocaloid
 *      producers, and anime artists likely to have TJ Media catalog entries.
 *   3. Appended a small curated additions list covering Hololive JP and
 *      Nijisanji JP talent and a few common chart artists not present in the
 *      blog corpus.
 *
 * Maintenance posture:
 *   Hand-maintained going forward. Same posture as
 *   `apps/web/src/data/featured.ts` — additions/removals land via PR with
 *   reasoning in the commit body. Names should match the form TJ's search
 *   field expects (Japanese script for Japanese acts, Latin for Latin-named
 *   acts; pipe-separated alias pairs are split into the canonical first
 *   segment when seeding from the blog corpus).
 */
export const ARTIST_SEED_LIST: readonly string[] = [
  // === Blog-corpus subset: well-known mainstream J-POP / rock / pop ===
  '[Alexandros]',
  '10-FEET',
  'Ado',
  'aiko',
  'Aimer',
  'amazarashi',
  'ano',
  'ASIAN KUNG-FU GENERATION',
  'Ayase',
  'back number',
  'BLUE ENCOUNT',
  'BoA',
  'BUMP OF CHICKEN',
  'Creepy Nuts',
  'DISH//',
  'DREAMS COME TRUE',
  'Eve',
  'flumpool',
  'GReeeeN',
  'Hump Back',
  'HY',
  'imase',
  'indigo la End',
  'JUDY AND MARY',
  'KANA-BOON',
  'King Gnu',
  'LiSA',
  'MAISONdes',
  'Mrs. GREEN APPLE',
  'MY FIRST STORY',
  'My Hair is Bad',
  'Novelbright',
  'Official髭男dism',
  'ONE OK ROCK',
  'RADWIMPS',
  'Reol',
  'ReoNa',
  'Saucy Dog',
  'SEKAI NO OWARI',
  'SPYAIR',
  'sumika',
  'SUPER BEAVER',
  'Superfly',
  'Tani Yuuki',
  'THE ORAL CIGARETTES',
  'tuki.',
  'UNISON SQUARE GARDEN',
  'Uru',
  'Vaundy',
  'wacci',
  'X JAPAN',
  'yama',
  'YOASOBI',
  'YUI',
  'あいみょん',
  'いしだあゆみ',
  'オーイシマサヨシ',
  'キタニタツヤ',
  'クリープハイプ',
  'サカナクション',
  'サザンオールスターズ',
  'スキマスイッチ',
  'ずっと真夜中でいいのに。',
  'スピッツ',
  'チョーキューメイ',
  'ナナヲアカリ',
  'なとり',
  'フレデリック',
  'ポルノグラフィティ',
  'マカロニえんぴつ',
  'ヨルシカ',
  '宇多田ヒカル',
  '安全地帯',
  '鬼頭明里',
  '玉置浩二',
  '桑田佳祐',
  '結束バンド',
  '高橋洋子',
  '坂本真綾',
  '山下達郎',
  '手嶌葵',
  '秋山黄色',
  '女王蜂',
  '松田聖子',
  '神聖かまってちゃん',
  '秦基博',
  '須田景凪',
  '水樹奈々',
  '菅田将暉',
  '星野源',
  '清水翔太',
  '中島みゆき',
  '中島美嘉',
  '椎名林檎',
  '藤井風',
  '尾崎豊',
  '美波',
  '福山雅治',
  '平井堅',
  '米津玄師',
  '優里',
  '羊文学',
  '緑黄色社会',
  '林原めぐみ',
  // === Blog-corpus subset: Vocaloid producers ===
  '40mP',
  'cosMo@暴走P',
  'DECO*27',
  'doriko',
  'Giga',
  'Kanaria',
  'kemu',
  'MARETU',
  'mothy_悪ノP',
  'Mitchie M',
  'Neru',
  'Orangestar',
  'OSTER project',
  'sasakure.UK',
  'supercell',
  'syudou',
  'wowaka',
  'いよわ',
  'かいりきベア',
  'カンザキイオリ',
  'きくお',
  'じん',
  'すりぃ',
  'ナユタン星人',
  'ハチ',
  'バルーン',
  'はるまきごはん',
  'ピノキオピー',
  'まふまふ',
  'みきとP',
  'ユリイ・カノン',
  '稲葉曇',
  '煮ル果実',
  '柊キライ',
  '八王子P',
  // === Curated additions: Hololive JP talent ===
  '星街すいせい',
  '宝鐘マリン',
  '森カリオペ',
  '常闇トワ',
  'コボ・カナエル',
  '兎田ぺこら',
  '湊あくあ',
  'AZKi',
  'IRyS',
  // === Curated additions: Nijisanji JP talent ===
  '葛葉',
  '叶',
  '月ノ美兎',
  '緑仙',
  // === Curated additions: chart/pop artists missing from the blog ===
  'Perfume',
  'EXILE',
  'ヒトリエ',
  'androp',
  'Cö shu Nie',
];
